apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: wp-backend
  labels:
    app: mysql
    tier: backend
spec: {}
status: {}
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: wp-backend-policy
#   namespace: wp-backend
#   labels:
#     app: mysql
#     tier: backend
# spec:
#   podSelector:
#     matchLabels:
#       role: db
#   policyTypes:
#   - Ingress
#   - Egress
#   ingress:
#   - from:
#     - ipBlock:
#         cidr: 172.17.0.0/16
#         except:
#         - 172.17.1.0/24
#     - namespaceSelector:
#         matchLabels:
#           project: myproject
#     - podSelector:
#         matchLabels:
#           role: backend
#     ports:
#     - protocol: TCP
#       port: 6379
#   egress:
#   - to:
#     - ipBlock:
#         cidr: 10.0.0.0/24
#     ports:
#     - protocol: TCP
#       port: 5978