apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: wp-backend
  labels:
    app: wordpress
    tier: backend
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None