apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wp-backend
  labels:
    app: mysql
    tier: backend
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: t0p-Secret