apiVersion: v1
kind: Service
metadata:
  name: wp-svc
  namespace: wp-frontend
  labels:
    app: wordpress
    tier: frontend
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer