apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
  namespace: wp-frontend
  labels:
    app: wordpress
    tier: frontend
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: t0p-Secret
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wp-frontend
  labels:
    app: mysql
    tier: frontend
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: t0p-Secret
